// src/components/settings/NotificationTest.jsx
import React, { useEffect, useState } from "react";
import { remoteClient } from "@/api/remoteClient";
import { AlertTriangle, CheckCircle, Loader2, MessageSquare, RefreshCw, Send, Timer, Wifi, XCircle } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";

function StatusRow({ label, ok, value }) {
  return (
    <div className="settings-test-row">
      <span>{label}</span>
      <strong>{value || (ok ? "configurado" : "pendente")}</strong>
      {ok ? <CheckCircle size={15} /> : <XCircle size={15} />}
    </div>
  );
}

export default function NotificationTest({ settings }) {
  const [testing, setTesting] = useState("");
  const [result, setResult] = useState(null);
  const [currentSettings, setCurrentSettings] = useState(settings);
  const [connStatus, setConnStatus] = useState(null);
  const [queueStatus, setQueueStatus] = useState(null);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    if (settings) setCurrentSettings(settings);
  }, [settings]);

  const reload = async () => {
    setLoading(true);
    try {
      const [freshSettings, queue] = await Promise.all([
        remoteClient.settings.get(),
        remoteClient.whatsapp.queueStatus().catch(() => null),
      ]);
      setCurrentSettings(freshSettings);
      setQueueStatus(queue);
    } finally {
      setLoading(false);
    }
  };

  const checkEvolutionConn = async () => {
    setConnStatus({ loading: true });
    try {
      const [status, queue] = await Promise.all([
        remoteClient.whatsapp.status(),
        remoteClient.whatsapp.queueStatus().catch(() => null),
      ]);
      setConnStatus({ data: status, ok: status.connected === true });
      setQueueStatus(queue);
    } catch (error) {
      setConnStatus({ error: error.message, ok: false });
    }
  };

  const runTest = async (type) => {
    setTesting(type);
    setResult(null);
    try {
      const destination = currentSettings?.admin_whatsapp;
      const labels = {
        admin: "Teste de novo pedido: uma recarga entrou na fila e aguarda processamento.",
        approval: "Teste de aprovacao: creditos liberados no painel.",
        rejection: "Teste de rejeicao: pedido recusado com motivo demonstrativo.",
      };
      const response = await remoteClient.whatsapp.test(destination, labels[type]);
      const queue = await remoteClient.whatsapp.queueStatus().catch(() => null);
      setQueueStatus(queue);
      setResult({ success: true, ...response });
      toast({ title: "Mensagem enfileirada", description: "O worker enviara respeitando os intervalos anti-ban." });
    } catch (error) {
      setResult({ error: error.message, success: false });
      toast({ title: "Falha no teste", description: error.message, variant: "destructive" });
    } finally {
      setTesting("");
    }
  };

  const hasEvolution = currentSettings?.evolution_api_url && currentSettings?.evolution_instance && currentSettings?.evolution_api_key;
  const hasAdmin = currentSettings?.admin_whatsapp;
  const throttle = queueStatus?.throttle || {};

  return (
    <div className="settings-form">
      <div className="settings-form-header">
        <div className="settings-form-icon">
          <MessageSquare size={18} />
        </div>
        <div>
          <h2>Testes de notificacao</h2>
          <p>Verifique Evolution API, fila anti-ban e mensagens de teste.</p>
        </div>
      </div>

      <section className="settings-test-panel">
        <div className="settings-form-header">
          <div className="settings-form-icon">
            <Wifi size={18} />
          </div>
          <div>
            <h2>Diagnostico Evolution API</h2>
            <p>Configuracao atual usada pelo backend.</p>
          </div>
        </div>

        <div className="settings-test-list">
          <StatusRow
            label="URL Base"
            ok={!!currentSettings?.evolution_api_url}
            value={currentSettings?.evolution_api_url ? `${currentSettings.evolution_api_url.substring(0, 30)}...` : null}
          />
          <StatusRow label="Instancia" ok={!!currentSettings?.evolution_instance} value={currentSettings?.evolution_instance || null} />
          <StatusRow
            label="API Key"
            ok={!!currentSettings?.evolution_api_key}
            value={currentSettings?.evolution_api_key ? `${currentSettings.evolution_api_key.substring(0, 8)}...` : null}
          />
          <StatusRow label="Admin WhatsApp" ok={!!currentSettings?.admin_whatsapp} value={currentSettings?.admin_whatsapp || null} />
        </div>

        <div className="settings-form-actions">
          <button disabled={loading} onClick={reload} type="button">
            <RefreshCw className={loading ? "settings-spin" : ""} size={15} />
            Recarregar
          </button>
          <button disabled={!hasEvolution || connStatus?.loading} onClick={checkEvolutionConn} type="button">
            {connStatus?.loading ? <Loader2 className="settings-spin" size={15} /> : <Wifi size={15} />}
            Checar conexao
          </button>
        </div>

        {connStatus && !connStatus.loading && (
          <div className={connStatus.ok ? "settings-success" : "settings-error"}>
            {connStatus.ok ? <CheckCircle size={15} /> : <AlertTriangle size={15} />}
            {connStatus.ok ? "Conectado" : `Desconectado${connStatus.error ? ` - ${connStatus.error}` : ""}`}
          </div>
        )}
      </section>

      {queueStatus && (
        <section className="settings-test-panel">
          <div className="settings-form-header">
            <div className="settings-form-icon">
              <Timer size={18} />
            </div>
            <div>
              <h2>Fila anti-ban</h2>
              <p>Status atual dos disparos enfileirados.</p>
            </div>
          </div>

          <div className="settings-queue-grid">
            <div><span>Aguardando</span><strong>{queueStatus.waiting ?? 0}</strong></div>
            <div><span>Agendadas</span><strong>{queueStatus.delayed ?? 0}</strong></div>
            <div><span>Ativas</span><strong>{queueStatus.active ?? 0}</strong></div>
            <div><span>Falhas</span><strong>{queueStatus.failed ?? 0}</strong></div>
          </div>
          <p className="settings-muted">
            Delay aleatorio: {Math.round((throttle.minDelayMs || 0) / 1000)}s a {Math.round((throttle.maxDelayMs || 0) / 1000)}s.
            Intervalo minimo: {Math.round((throttle.minSendIntervalMs || 0) / 1000)}s.
          </p>
        </section>
      )}

      {!hasEvolution && (
        <div className="settings-error">
          <AlertTriangle size={15} />
          Configure a Evolution API na aba Integracoes antes de testar.
        </div>
      )}

      <section className="settings-test-panel">
        <div className="settings-form-header">
          <div className="settings-form-icon">
            <Send size={18} />
          </div>
          <div>
            <h2>Mensagens de teste</h2>
            <p>Destino: {currentSettings?.admin_whatsapp || "numero nao configurado"}</p>
          </div>
        </div>

        <div className="settings-test-actions">
          {[
            ["admin", "Testar novo pedido"],
            ["approval", "Testar aprovacao"],
            ["rejection", "Testar rejeicao"],
          ].map(([type, label]) => (
            <button disabled={!hasEvolution || !hasAdmin || Boolean(testing)} key={type} onClick={() => runTest(type)} type="button">
              {testing === type ? <Loader2 className="settings-spin" size={15} /> : <Send size={15} />}
              {label}
            </button>
          ))}
        </div>

        {result && (
          <div className={result.success ? "settings-success" : "settings-error"}>
            {result.success ? <CheckCircle size={15} /> : <AlertTriangle size={15} />}
            {result.success ? `Enfileirado. Log: ${result.logId || "-"}` : result.error}
          </div>
        )}
      </section>
    </div>
  );
}

// frontend-vue/src/modules/settings/components/NotificationTest.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'

import { useWhatsappTest } from '../composables/useWhatsappTest'
import type { AdminSettings } from '../types'

const props = defineProps<{
  settings: AdminSettings | null
}>()

const { conn, queue, testing, result, loadQueue, checkConnection, sendTest } = useWhatsappTest()

const hasEvolution = computed(
  () => Boolean(props.settings?.evolution_api_url && props.settings?.evolution_instance && props.settings?.evolution_api_key),
)
const adminPhone = computed(() => props.settings?.admin_whatsapp ?? '')

const TESTS: { type: string; label: string; message: string }[] = [
  { type: 'admin', label: 'Testar novo pedido', message: 'Teste de novo pedido: uma recarga entrou na fila e aguarda processamento.' },
  { type: 'approval', label: 'Testar aprovação', message: 'Teste de aprovação: créditos liberados no painel.' },
  { type: 'rejection', label: 'Testar rejeição', message: 'Teste de rejeição: pedido recusado com motivo demonstrativo.' },
]

const statusRows = computed(() => [
  { label: 'URL Base', ok: Boolean(props.settings?.evolution_api_url), value: props.settings?.evolution_api_url },
  { label: 'Instância', ok: Boolean(props.settings?.evolution_instance), value: props.settings?.evolution_instance },
  { label: 'API Key', ok: Boolean(props.settings?.evolution_api_key), value: props.settings?.evolution_api_key ? `${props.settings.evolution_api_key.slice(0, 8)}...` : '' },
  { label: 'Admin WhatsApp', ok: Boolean(adminPhone.value), value: adminPhone.value },
])

const sec = (ms?: number) => Math.round((ms || 0) / 1000)

function runTest(type: string, message: string) {
  if (!adminPhone.value) return
  sendTest(type, adminPhone.value, message)
}

onMounted(loadQueue)
</script>

<template>
  <div class="set-form">
    <div class="set-head">
      <div class="set-head-icon">📨</div>
      <div>
        <h2>Testes de notificação</h2>
        <p>Verifique Evolution API, fila anti-ban e mensagens de teste.</p>
      </div>
    </div>

    <section class="set-section">
      <h3>Diagnóstico Evolution API</h3>
      <p>Configuração atual usada pelo backend.</p>
      <div class="nt-status">
        <div v-for="row in statusRows" :key="row.label" class="nt-status-row">
          <span>{{ row.label }}</span>
          <strong>{{ row.value || (row.ok ? 'configurado' : 'pendente') }}</strong>
          <em :class="row.ok ? 'ok' : 'off'">{{ row.ok ? '✓' : '✕' }}</em>
        </div>
      </div>
      <div class="set-actions">
        <button class="set-btn" type="button" :disabled="!hasEvolution || conn?.loading" @click="checkConnection">
          {{ conn?.loading ? 'Checando...' : 'Checar conexão' }}
        </button>
      </div>
      <div v-if="conn && !conn.loading" :class="conn.ok ? 'set-success' : 'set-error'">
        {{ conn.ok ? 'Conectado' : `Desconectado${conn.message ? ' — ' + conn.message : ''}` }}
      </div>
    </section>

    <section v-if="queue" class="set-section">
      <h3>Fila anti-ban</h3>
      <p>Status atual dos disparos enfileirados.</p>
      <div class="nt-queue">
        <div><span>Aguardando</span><strong>{{ queue.waiting ?? 0 }}</strong></div>
        <div><span>Agendadas</span><strong>{{ queue.delayed ?? 0 }}</strong></div>
        <div><span>Ativas</span><strong>{{ queue.active ?? 0 }}</strong></div>
        <div><span>Falhas</span><strong>{{ queue.failed ?? 0 }}</strong></div>
      </div>
      <p class="set-note">
        Delay aleatório: {{ sec(queue.throttle?.minDelayMs) }}s a {{ sec(queue.throttle?.maxDelayMs) }}s.
        Intervalo mínimo: {{ sec(queue.throttle?.minSendIntervalMs) }}s.
      </p>
    </section>

    <div v-if="!hasEvolution" class="set-error">
      Configure a Evolution API na aba WhatsApp antes de testar.
    </div>

    <section class="set-section">
      <h3>Mensagens de teste</h3>
      <p>Destino: {{ adminPhone || 'número não configurado' }}</p>
      <div class="nt-tests">
        <button
          v-for="test in TESTS"
          :key="test.type"
          class="set-btn"
          type="button"
          :disabled="!hasEvolution || !adminPhone || Boolean(testing)"
          @click="runTest(test.type, test.message)"
        >
          {{ testing === test.type ? 'Enviando...' : test.label }}
        </button>
      </div>
      <div v-if="result" :class="result.success ? 'set-success' : 'set-error'">
        {{ result.success ? `Enfileirado. Log: ${result.logId || '-'}` : result.error }}
      </div>
    </section>
  </div>
</template>

<style scoped>
.nt-status {
  display: grid;
  gap: 9px;
}

.nt-status-row {
  display: grid;
  grid-template-columns: 150px minmax(0, 1fr) auto;
  gap: 10px;
  align-items: center;
  padding: 12px 14px;
  border-radius: 14px;
  background: #fff;
  border: 1px solid var(--gj2-line);
}

.nt-status-row span {
  color: var(--gj2-muted);
  font-size: 12px;
  font-weight: 760;
}

.nt-status-row strong {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--gj2-ink);
  font-size: 13px;
}

.nt-status-row em {
  font-style: normal;
  font-weight: 900;
}

.nt-status-row em.ok { color: #3f7d63; }
.nt-status-row em.off { color: #c23b34; }

.nt-queue {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 10px;
}

.nt-queue div {
  padding: 12px;
  border-radius: 14px;
  background: #fff;
  border: 1px solid var(--gj2-line);
}

.nt-queue span {
  color: var(--gj2-muted);
  font-size: 11px;
  font-weight: 760;
  text-transform: uppercase;
}

.nt-queue strong {
  display: block;
  margin-top: 5px;
  color: var(--gj2-green-deep);
  font-size: 24px;
  font-weight: 870;
}

.nt-tests {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 10px;
}

@media (max-width: 720px) {
  .nt-status-row,
  .nt-queue,
  .nt-tests {
    grid-template-columns: 1fr;
  }
}
</style>
