// frontend-vue/src/modules/settings/components/IntegrationsForm.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'

import type { AdminSettings } from '../types'

const props = defineProps<{
  settings: AdminSettings | null
  save: (patch: Partial<AdminSettings>) => Promise<AdminSettings>
}>()

const form = reactive({
  evolution_api_url: props.settings?.evolution_api_url ?? '',
  evolution_instance: props.settings?.evolution_instance ?? props.settings?.evolution_instance_id ?? '',
  evolution_api_key: props.settings?.evolution_api_key ?? '',
  admin_whatsapp: props.settings?.admin_whatsapp ?? '',
  n8n_webhook_url: props.settings?.n8n_webhook_url ?? '',
  fcm_server_key: props.settings?.fcm_server_key ?? '',
})

const saving = ref(false)
const success = ref(false)
const error = ref('')

watch(
  () => props.settings,
  (settings) => {
    form.evolution_api_url = settings?.evolution_api_url ?? ''
    form.evolution_instance = settings?.evolution_instance ?? settings?.evolution_instance_id ?? ''
    form.evolution_api_key = settings?.evolution_api_key ?? ''
    form.admin_whatsapp = settings?.admin_whatsapp ?? ''
    form.n8n_webhook_url = settings?.n8n_webhook_url ?? ''
    form.fcm_server_key = settings?.fcm_server_key ?? ''
  },
  { immediate: true },
)

const hasEvolution = computed(
  () => Boolean(form.evolution_api_url && form.evolution_api_key && form.evolution_instance),
)

const diagnostics = computed(() => [
  { label: 'URL Base', value: form.evolution_api_url },
  { label: 'Instância', value: form.evolution_instance },
  { label: 'API Key', value: form.evolution_api_key ? `${form.evolution_api_key.slice(0, 8)}...` : '' },
  { label: 'Admin WhatsApp', value: form.admin_whatsapp },
])

async function submit() {
  saving.value = true
  success.value = false
  error.value = ''
  try {
    await props.save({ ...form, whatsapp_provider: 'evolution' })
    success.value = true
    setTimeout(() => (success.value = false), 4000)
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Erro ao salvar.'
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <form class="set-form" @submit.prevent="submit">
    <div class="set-head">
      <div class="set-head-icon">💬</div>
      <div>
        <h2>Integrações</h2>
        <p>Configure WhatsApp, automações e notificações externas.</p>
      </div>
    </div>

    <div v-if="success" class="set-success">Configurações salvas.</div>
    <div v-if="error" class="set-error">{{ error }}</div>

    <section class="set-section">
      <h3>Evolution API</h3>
      <p>Envio de notificações via WhatsApp com fila segura.</p>

      <div :class="hasEvolution ? 'set-success' : 'set-error'">
        {{ hasEvolution ? 'Evolution API configurada.' : 'Preencha URL, instância e API key para ativar o WhatsApp.' }}
      </div>

      <div class="set-grid">
        <label class="set-field">
          <span>URL Base da Evolution API</span>
          <input v-model="form.evolution_api_url" placeholder="https://evolution.suaempresa.com" />
          <small>Ex: https://evolution.suaempresa.com</small>
        </label>
        <label class="set-field">
          <span>Instância</span>
          <input v-model="form.evolution_instance" placeholder="gestor-j2" />
          <small>Nome/id da instância criada na Evolution API.</small>
        </label>
        <label class="set-field">
          <span>API Key Global</span>
          <input v-model="form.evolution_api_key" type="password" placeholder="sua-api-key-aqui" />
          <small>Chave enviada no header apikey.</small>
        </label>
        <label class="set-field">
          <span>WhatsApp do admin</span>
          <input v-model="form.admin_whatsapp" placeholder="49998298148" />
          <small>Número que recebe alertas de novos pedidos (só dígitos com DDD).</small>
        </label>
      </div>

      <router-link class="set-btn" to="/whatsapp">Abrir WhatsApp / Diagnóstico →</router-link>
    </section>

    <section class="set-section">
      <h3>n8n Webhook</h3>
      <p>Automações opcionais quando pedidos mudam de estado.</p>
      <label class="set-field full">
        <span>URL do webhook</span>
        <input v-model="form.n8n_webhook_url" placeholder="https://n8n.exemplo.com/webhook/..." />
        <small>Opcional.</small>
      </label>
    </section>

    <section class="set-section">
      <h3>Firebase Cloud Messaging</h3>
      <p>Chave opcional para notificações push no navegador.</p>
      <label class="set-field full">
        <span>FCM Server Key</span>
        <textarea v-model="form.fcm_server_key" rows="3" placeholder="AAAA..." />
        <small>Opcional.</small>
      </label>
    </section>

    <section class="set-section diag">
      <div v-for="item in diagnostics" :key="item.label" class="diag-row">
        <span>{{ item.value ? '✓' : '✕' }} {{ item.label }}</span>
        <strong>{{ item.value || 'não configurado' }}</strong>
      </div>
    </section>

    <div class="set-actions">
      <button class="set-btn set-btn--primary" type="submit" :disabled="saving">
        {{ saving ? 'Salvando...' : 'Salvar integrações' }}
      </button>
    </div>
  </form>
</template>

<style scoped>
.diag {
  gap: 8px;
}

.diag-row {
  display: grid;
  grid-template-columns: 160px minmax(0, 1fr);
  gap: 10px;
  align-items: center;
  color: var(--gj2-muted);
  font-size: 12.5px;
}

.diag-row strong {
  color: var(--gj2-ink);
  font-weight: 760;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

@media (max-width: 560px) {
  .diag-row {
    grid-template-columns: 1fr;
    gap: 2px;
  }
}
</style>

// src/components/settings/IntegrationsForm.jsx
import React, { useEffect, useState } from "react";
import { remoteClient } from "@/api/remoteClient";
import { AlertTriangle, CheckCircle, ExternalLink, Link2, MessageSquare, Save, Smartphone, Webhook, XCircle } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";

function Field({ children, hint, label }) {
  return (
    <label className="settings-field">
      <span>{label}</span>
      {children}
      {hint && <small>{hint}</small>}
    </label>
  );
}

export default function IntegrationsForm({ settings, onUpdate }) {
  const [formData, setFormData] = useState({
    admin_whatsapp: settings?.admin_whatsapp || "",
    evolution_api_key: settings?.evolution_api_key || "",
    evolution_api_url: settings?.evolution_api_url || "",
    evolution_instance: settings?.evolution_instance || settings?.evolution_instance_id || "",
    fcm_server_key: settings?.fcm_server_key || "",
    n8n_webhook_url: settings?.n8n_webhook_url || "",
    whatsapp_provider: "evolution",
  });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");
  const { toast } = useToast();

  useEffect(() => {
    if (!settings) return;
    setFormData({
      admin_whatsapp: settings.admin_whatsapp || "",
      evolution_api_key: settings.evolution_api_key || "",
      evolution_api_url: settings.evolution_api_url || "",
      evolution_instance: settings.evolution_instance || settings.evolution_instance_id || "",
      fcm_server_key: settings.fcm_server_key || "",
      n8n_webhook_url: settings.n8n_webhook_url || "",
      whatsapp_provider: "evolution",
    });
  }, [settings]);

  const update = (key, value) => setFormData((current) => ({ ...current, [key]: value }));

  const handleSubmit = async (event) => {
    event.preventDefault();
    setLoading(true);
    setError("");
    setSuccess(false);
    try {
      const updated = await remoteClient.settings.update({
        ...formData,
        whatsapp_provider: "evolution",
      });
      onUpdate(updated);
      setSuccess(true);
      toast({ title: "Configuracoes salvas", description: "Evolution API atualizada com sucesso." });
      setTimeout(() => setSuccess(false), 5000);
    } catch (err) {
      setError(err.message || "Erro ao salvar");
      toast({ title: "Erro ao salvar", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const hasEvolutionConfig = formData.evolution_api_url && formData.evolution_api_key && formData.evolution_instance;

  return (
    <form className="settings-form" onSubmit={handleSubmit}>
      <div className="settings-form-header">
        <div className="settings-form-icon">
          <MessageSquare size={18} />
        </div>
        <div>
          <h2>Integracoes</h2>
          <p>Configure WhatsApp, automacoes e notificacoes externas.</p>
        </div>
      </div>

      {success && (
        <div className="settings-success">
          <CheckCircle size={15} /> Configuracoes salvas.
        </div>
      )}
      {error && (
        <div className="settings-error">
          <AlertTriangle size={15} /> {error}
        </div>
      )}

      <section className="settings-form-section">
        <div className="settings-form-header">
          <div className="settings-form-icon">
            <Smartphone size={18} />
          </div>
          <div>
            <h2>Evolution API</h2>
            <p>Envio de notificacoes via WhatsApp com fila segura.</p>
          </div>
        </div>

        <div className={hasEvolutionConfig ? "settings-success" : "settings-error"} style={{ marginTop: 12 }}>
          {hasEvolutionConfig ? <CheckCircle size={15} /> : <AlertTriangle size={15} />}
          {hasEvolutionConfig ? "Evolution API configurada." : "Preencha URL, instancia e API key para ativar o WhatsApp."}
        </div>

        <div className="settings-grid" style={{ marginTop: 12 }}>
          <Field label="URL Base da Evolution API" hint="Ex: https://evolution.suaempresa.com">
            <input
              onChange={(event) => update("evolution_api_url", event.target.value)}
              placeholder="https://evolution.suaempresa.com"
              value={formData.evolution_api_url}
            />
          </Field>

          <Field label="Instancia" hint="Nome/id da instancia criada na Evolution API">
            <input
              onChange={(event) => update("evolution_instance", event.target.value)}
              placeholder="gestor-j2"
              value={formData.evolution_instance}
            />
          </Field>

          <Field label="API Key Global" hint="Chave enviada no header apikey">
            <input
              onChange={(event) => update("evolution_api_key", event.target.value)}
              placeholder="sua-api-key-aqui"
              type="password"
              value={formData.evolution_api_key}
            />
          </Field>

          <Field label="WhatsApp do admin" hint="Numero que recebe alertas de novos pedidos, apenas digitos com DDD">
            <input
              onChange={(event) => update("admin_whatsapp", event.target.value)}
              placeholder="49998298148"
              value={formData.admin_whatsapp}
            />
          </Field>
        </div>

        <a className="settings-action" href="/whatsappdiagnostic" style={{ marginTop: 12, textDecoration: "none" }}>
          Abrir WA Diagnostico <ExternalLink size={14} />
        </a>
      </section>

      <section className="settings-form-section">
        <div className="settings-form-header">
          <div className="settings-form-icon">
            <Webhook size={18} />
          </div>
          <div>
            <h2>n8n Webhook</h2>
            <p>Automacoes opcionais quando pedidos mudam de estado.</p>
          </div>
        </div>
        <div className="settings-grid" style={{ marginTop: 12 }}>
          <Field label="URL do webhook" hint="Opcional">
            <input
              onChange={(event) => update("n8n_webhook_url", event.target.value)}
              placeholder="https://n8n.exemplo.com/webhook/..."
              value={formData.n8n_webhook_url}
            />
          </Field>
        </div>
      </section>

      <section className="settings-form-section">
        <div className="settings-form-header">
          <div className="settings-form-icon">
            <Link2 size={18} />
          </div>
          <div>
            <h2>Firebase Cloud Messaging</h2>
            <p>Chave opcional para notificacoes push no navegador.</p>
          </div>
        </div>
        <div className="settings-grid" style={{ marginTop: 12 }}>
          <Field label="FCM Server Key" hint="Opcional">
            <textarea
              onChange={(event) => update("fcm_server_key", event.target.value)}
              placeholder="AAAA..."
              rows={3}
              value={formData.fcm_server_key}
            />
          </Field>
        </div>
      </section>

      <section className="settings-diagnostic">
        {[
          ["URL Base", formData.evolution_api_url],
          ["Instancia", formData.evolution_instance],
          ["API Key", formData.evolution_api_key ? `${formData.evolution_api_key.slice(0, 8)}...` : ""],
          ["Admin WhatsApp", formData.admin_whatsapp],
        ].map(([label, value]) => (
          <div key={label}>
            <span>{value ? <CheckCircle size={13} /> : <XCircle size={13} />} {label}</span>
            <strong>{value || "nao configurado"}</strong>
          </div>
        ))}
      </section>

      <div className="settings-form-actions">
        <button className="settings-save" disabled={loading} type="submit">
          <Save size={15} />
          {loading ? "Salvando..." : "Salvar integracoes"}
        </button>
      </div>
    </form>
  );
}
