// frontend-vue/src/modules/settings/components/PixForm.vue
<script setup lang="ts">
import { reactive, ref, watch } from 'vue'

import { PIX_KEY_TYPES, type AdminSettings, type PixKey } from '../types'

const props = defineProps<{
  settings: AdminSettings | null
  save: (patch: Partial<AdminSettings>) => Promise<AdminSettings>
}>()

const keys = ref<PixKey[]>([...(props.settings?.pix_keys ?? [])])
const newKey = reactive<PixKey>({ type: '', key_value: '', bank: '', is_active: true })
const saving = ref(false)
const success = ref(false)
const error = ref('')

watch(
  () => props.settings?.pix_keys,
  (pixKeys) => {
    keys.value = [...(pixKeys ?? [])]
  },
  { immediate: true },
)

function addKey() {
  if (!newKey.type || !newKey.key_value || !newKey.bank) {
    error.value = 'Preencha tipo, valor e banco antes de adicionar.'
    return
  }
  error.value = ''
  keys.value.push({ ...newKey, id: Date.now() })
  newKey.type = ''
  newKey.key_value = ''
  newKey.bank = ''
  newKey.is_active = true
}

function removeKey(index: number) {
  keys.value.splice(index, 1)
}

function toggleActive(index: number) {
  keys.value[index].is_active = !keys.value[index].is_active
}

async function save() {
  saving.value = true
  success.value = false
  error.value = ''
  try {
    await props.save({ pix_keys: keys.value })
    success.value = true
    setTimeout(() => (success.value = false), 3000)
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Não foi possível salvar.'
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <div class="set-form">
    <div class="set-head">
      <div class="set-head-icon">🔑</div>
      <div>
        <h2>Chaves PIX</h2>
        <p>Gerencie as chaves disponíveis para recebimento.</p>
      </div>
    </div>

    <div v-if="success" class="set-success">Chaves PIX salvas com sucesso.</div>
    <div v-if="error" class="set-error">{{ error }}</div>

    <section class="set-section">
      <h3>Chaves cadastradas</h3>
      <p>{{ keys.length }} chave(s) configurada(s).</p>

      <div v-if="keys.length === 0" class="set-empty">Nenhuma chave PIX cadastrada.</div>
      <div v-else class="pix-list">
        <article v-for="(key, index) in keys" :key="`${key.key_value}-${index}`" class="pix-row" :class="{ off: !key.is_active }">
          <div class="pix-info">
            <strong>{{ PIX_KEY_TYPES[key.type] || key.type }} · {{ key.bank }}</strong>
            <span>{{ key.key_value }}</span>
          </div>
          <div class="pix-actions">
            <button class="set-btn" type="button" @click="toggleActive(index)">
              {{ key.is_active ? 'Desativar' : 'Ativar' }}
            </button>
            <button class="set-btn set-btn--danger" type="button" @click="removeKey(index)">Remover</button>
          </div>
        </article>
      </div>
    </section>

    <section class="set-section">
      <h3>Adicionar nova chave</h3>
      <p>Preencha os dados e clique em adicionar antes de salvar.</p>

      <div class="set-grid">
        <label class="set-field">
          <span>Tipo de chave</span>
          <select v-model="newKey.type">
            <option value="">Selecione</option>
            <option v-for="(label, value) in PIX_KEY_TYPES" :key="value" :value="value">{{ label }}</option>
          </select>
        </label>
        <label class="set-field">
          <span>Valor da chave PIX</span>
          <input v-model="newKey.key_value" placeholder="ex: 00000000000" />
        </label>
        <label class="set-field full">
          <span>Nome do banco</span>
          <input v-model="newKey.bank" placeholder="ex: Nubank" />
        </label>
      </div>

      <div class="set-actions">
        <button class="set-btn" type="button" @click="addKey">Adicionar chave</button>
        <button class="set-btn set-btn--primary" type="button" :disabled="saving" @click="save">
          {{ saving ? 'Salvando...' : 'Salvar configurações' }}
        </button>
      </div>
    </section>
  </div>
</template>

<style scoped>
.pix-list {
  display: grid;
  gap: 10px;
}

.pix-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 12px;
  align-items: center;
  padding: 14px;
  border-radius: 16px;
  background: #fff;
  border: 1px solid var(--gj2-line);
}

.pix-row.off {
  opacity: 0.6;
}

.pix-info strong {
  display: block;
  color: var(--gj2-ink);
  font-size: 14px;
  font-weight: 830;
}

.pix-info span {
  display: block;
  margin-top: 3px;
  color: var(--gj2-muted);
  font-size: 13px;
  word-break: break-word;
}

.pix-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  justify-content: flex-end;
}

.pix-actions .set-btn {
  min-height: 40px;
  padding: 0 14px;
  font-size: 13px;
}

@media (max-width: 560px) {
  .pix-row {
    grid-template-columns: 1fr;
  }

  .pix-actions {
    justify-content: stretch;
  }
}
</style>

// src/components/settings/PixForm.jsx
import React, { useState } from "react";
import { remoteClient } from "@/api/remoteClient";
import { CheckCircle, Key, Plus, Save, Trash2 } from "lucide-react";

const keyTypes = {
  cnpj: "CNPJ",
  cpf: "CPF",
  email: "Email",
  phone: "Telefone",
  random: "Chave Aleatoria",
};

export default function PixForm({ settings, onUpdate }) {
  const [pixKeys, setPixKeys] = useState(settings?.pix_keys || []);
  const [newKey, setNewKey] = useState({ bank: "", is_active: true, key_value: "", type: "" });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  const updateNewKey = (key, value) => setNewKey((current) => ({ ...current, [key]: value }));

  const handleAddKey = () => {
    if (!newKey.type || !newKey.key_value || !newKey.bank) {
      alert("Preencha todos os campos: Tipo, Valor e Banco.");
      return;
    }
    setPixKeys([...pixKeys, { ...newKey, id: Date.now() }]);
    setNewKey({ bank: "", is_active: true, key_value: "", type: "" });
  };

  const handleRemoveKey = (index) => setPixKeys(pixKeys.filter((_, keyIndex) => keyIndex !== index));

  const handleToggleActive = (index) => {
    setPixKeys(pixKeys.map((key, keyIndex) => (keyIndex === index ? { ...key, is_active: !key.is_active } : key)));
  };

  const handleSave = async () => {
    setLoading(true);
    try {
      const updated = await remoteClient.settings.update({ pix_keys: pixKeys });
      onUpdate(updated);
      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (error) {
      console.error("[PixForm] save error:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="settings-form">
      <div className="settings-form-header">
        <div className="settings-form-icon">
          <Key size={18} />
        </div>
        <div>
          <h2>Chaves PIX</h2>
          <p>Gerencie as chaves disponiveis para recebimento.</p>
        </div>
      </div>

      {success && (
        <div className="settings-success">
          <CheckCircle size={15} /> Chaves PIX salvas com sucesso.
        </div>
      )}

      <section className="settings-form-section">
        <h3>Chaves cadastradas</h3>
        <p>{pixKeys.length} chave(s) configuradas.</p>

        <div className="settings-pix-list" style={{ marginTop: 12 }}>
          {pixKeys.length === 0 ? (
            <div className="settings-empty">Nenhuma chave PIX cadastrada.</div>
          ) : (
            pixKeys.map((key, index) => (
              <article className="settings-pix-row" key={`${key.key_value}-${index}`}>
                <div>
                  <strong>{keyTypes[key.type] || key.type} - {key.bank}</strong>
                  <span>{key.key_value}</span>
                </div>
                <div className="settings-pix-actions">
                  <button onClick={() => handleToggleActive(index)} type="button">
                    {key.is_active ? "Desativar" : "Ativar"}
                  </button>
                  <button onClick={() => handleRemoveKey(index)} type="button">
                    <Trash2 size={14} />
                    Remover
                  </button>
                </div>
              </article>
            ))
          )}
        </div>
      </section>

      <section className="settings-form-section">
        <h3>Adicionar nova chave</h3>
        <p>Preencha os dados e clique em adicionar antes de salvar.</p>

        <div className="settings-grid" style={{ marginTop: 12 }}>
          <label className="settings-field">
            <span>Tipo de chave</span>
            <select onChange={(event) => updateNewKey("type", event.target.value)} value={newKey.type}>
              <option value="">Selecione</option>
              {Object.entries(keyTypes).map(([value, label]) => (
                <option key={value} value={value}>{label}</option>
              ))}
            </select>
          </label>

          <label className="settings-field">
            <span>Valor da chave PIX</span>
            <input
              onChange={(event) => updateNewKey("key_value", event.target.value)}
              placeholder="ex: 00000000000"
              value={newKey.key_value}
            />
          </label>

          <label className="settings-field full">
            <span>Nome do banco</span>
            <input
              onChange={(event) => updateNewKey("bank", event.target.value)}
              placeholder="ex: Nubank"
              value={newKey.bank}
            />
          </label>
        </div>

        <div className="settings-form-actions" style={{ marginTop: 12 }}>
          <button onClick={handleAddKey} type="button">
            <Plus size={15} />
            Adicionar chave
          </button>
          <button className="settings-save" disabled={loading} onClick={handleSave} type="button">
            <Save size={15} />
            {loading ? "Salvando..." : "Salvar configuracoes"}
          </button>
        </div>
      </section>
    </div>
  );
}
